### ISSUE TITLE
Stream Downloads

### ISSUE THREAD

**Issue by mitsuhiko** [durch/rust-s3#10]
Currently the library only supports downloading into a vector. I have some large files I want to write directly to at the least the file system or better, pipe it into a `XzDecoder`. I do not see a good way to make this work at the moment.

Ideally there is a `fn get_stream` which returns an iterator or a file you can read from.

**Comment by durch** [comment]
I'll look into it, can't really promise anything, but it could make for an interesting implementation, @mitsuhiko would you like to take a stab at it :)

**Comment by golddranks** [comment]
I, too would be happy about that kind of functionality :)

**Comment by ford-prefect** [comment]
fwiw, I ended up adding this to Rusoto in this PR -- https://github.com/rusoto/rusoto/pull/627

**Comment by durch** [comment]
@golddranks well I can promise I'll look into it :), but can't commit to a timeline. @nastevens  is this something you'd have an interest in implementing?

**Comment by blakesmith** [comment]
@durch I need to add S3 to a Rust project of mine, and streaming upload / download is going to be important. I've looked at [rusoto](https://github.com/rusoto/rusoto), but prefer blocking IO via a `Read` and `Write` interface in the context I'm working in. A full on Future / Stream / tokio setup just doesn't make sense.

My plan was to use your library as a starting point, fork, and add streaming download and multipart upload support - via the aforementiond `std::io` traits. Would you be interested in patches that add this?

**Comment by durch** [comment]
Absolutely, last time I looked into this it seemed like too much of a hassle without a defined use case. Sounds like you have one, and I'd be more than happy to take the patch and help as needed :)
