### ISSUE TITLE
Adding to dependencies in rust-wasm project causing errors

### ISSUE THREAD

**Issue by will-sloan** [durch/rust-s3#102]
**Describe the bug**
When adding `rust-s3 = "0.22.12"` to my dependencies in a rust-wasm project, it causes the build to fail.   
Mainly it says: `unresolved import 'sys'`

**To Reproduce**
Create a rust-wasm project and add rust-s3
you can follow [this](https://rustwasm.github.io/docs/book/game-of-life/setup.html)  
Then: 
1 - `cargo generate --git https://github.com/rustwasm/wasm-pack-template`
2 - Enter any name
3 - Add rust-s3 to `Cargo.toml`
4 - `wasm-pack build`

**Expected behavior**
For it to build.

**Environment**
 - Rust version: [`1.44`]
 - wasm-bindgen = "0.2.63"
 - rust-s3 = "0.22.12"

**Comment by durch** [comment]
@will-sloan thank you for raising this, core problem is the `reqwest` dependency, it does most of its work through `tokio` which deep down depends on `net2` which is not `wasm` compatible. I wanted to replace reqwest with something more lightweight a while now, and this is a perfect excuse. I'm hoping to address it fairly quickly, however it is a major undertaking so I'm not super confident in that estimate, anyway I'll keep this issue updated with progress

**Comment by durch** [comment]
@will-sloan I'd be curious to see if `v0.23.0-beta2` meets your requirements, functionally its probably as good as it gets, I have a lot of clean up to do but should be good otherwise

**Comment by will-sloan** [comment]
@durch I put `rust-s3 = "0.23.0-beta1"` which compiled (only included in Cargo.toml, it hasn't been used yet). There doesn't seem to be a `0.23.0-beta2` unless I'm missing something.

**Comment by durch** [comment]
@will-sloan, terribly sorry about the version mix up, I guess I forgot to actually publish once the CI went green, anyway `beta2` is published now, until it gets merged this should get you going:

```toml
rust-s3 = {version = "0.23.0-beta2", features = ["wasm"], default-features = false}
```

**Comment by will-sloan** [comment]
Thanks, seems to be working.

**Comment by durch** [comment]
Beautiful, I'll do some more cleanup, and than merge to master
