### ISSUE TITLE
put_object_stream_blocking uploads 0B file

### ISSUE THREAD

**Issue by jaredwolff** [durch/rust-s3#106]
**Describe the bug**
When using `put_object_stream_blocking`, I went to check the results of the file upload only to find 0B file of the correct name.

**To Reproduce**
Using a String or Path, open the file

```
// Open and upload file
let path = Path::new(&s.file);
if !path.exists() {
  error!("{} not found!", path.to_str().unwrap());
  std::process::exit(1);
}

let mut file = File::open(path).expect("Unable to open file!");

let status_code = bucket
.put_object_stream_blocking(&mut file, &server_filename)
.unwrap_or_else(|e| {
  error!("Unable to upload {}! Error: {}", &server_filename, e);
  std::process::exit(1);
});

println!("Status code: {}", status_code);
```
**Expected behavior**
The file is currently 180KB. I expect that to be reflected in what's uploaded to AWS.

**Environment**
 - Rust version: 1.45.0
 - lib version: 0.22.12

**Additional context**
Context: I'm uploading a firmware binary file.

**Comment by jaredwolff** [comment]
My workaround for now is to read the whole file into memory and use `put_object_blocking`. Not ideal but I'm not working with big files. 

```
      // Open the file
      let mut file = File::open(path).expect("Unable to open file!");

      let mut buffer = Vec::new();
      // read the whole file
      file
        .read_to_end(&mut buffer)
        .expect("Unable to read to end");

      // Upload file to AWS
      let (_, status_code) = bucket
        .put_object_blocking(&server_filename, &buffer, "application/octet-stream")
        .unwrap_or_else(|e| {
          error!("Unable to upload {}! Error: {}", &server_filename, e);
          std::process::exit(1);
        });
```

**Comment by durch** [comment]
@jaredwolff thank you for raising the issue, I'll look into it ASAP

**Comment by jiangplus** [comment]
I came into the same issue too.
The put_object_stream_blocking just uploaded an empty file, discarding the content.

**Comment by durch** [comment]
@jaredwolff, @jiangplus version `0.23` released today fixes this

**Comment by Qwertie-** [comment]
This is very likely not the same issue but I had a problem with the same result. Problem was I needed to reset the pointer for the file with `file.seek(SeekFrom::Start(0)).await?;` before uploading.
