### ISSUE TITLE
Etag function needed for non MD5 e-tags

### ISSUE THREAD

**Issue by jrmiller82** [durch/rust-s3#122]
The library needs a function to let the user generate a non MD5 e-tag on a local file so that it can do a comparison. 

See these links for the algorithm and rationale:

https://teppen.io/2018/06/23/aws_s3_etags/
https://teppen.io/2018/10/23/aws_s3_verify_etags/

**Comment by durch** [comment]
@jrmiller82 always happy to implement new use cases, will keep you posted

**Comment by durch** [comment]
Published in `0.26.1`
