### ISSUE TITLE
Docs: need updates to examples in docs to take into account correct useage of Credentials and Region

### ISSUE THREAD

**Issue by jrmiller82** [durch/rust-s3#123]
The docs throughout don't seem to take into account the re-exports of Credentials and Region.

**Comment by durch** [comment]
@jrmiller82 thank you for raising this, I'll make sure to update the docs

**Comment by jrmiller82** [comment]
Thank you!

**Comment by jrmiller82** [comment]
Just noticed there is still documentation in the comments that aren't correct: 

see https://docs.rs/rust-s3/0.26.0/s3/bucket/struct.Bucket.html#structfield.extra_headers
