### ISSUE TITLE
Missing bucket operations

### ISSUE THREAD

**Issue by floriama** [durch/rust-s3#127]
Hi,
I am in the process of evaluating if this crate fits my needs. From reading the docs I'm left wondering if operations to list all buckets and create / delete buckets are missing. 
Is this planned for the future or is this functionality omitted by design?

PS: Great crate, thanks for you work!

**Comment by durch** [comment]
@floriama I'm planning to support the full API eventually, I take a stab at implementing bucket ops, and report back

**Comment by floriama** [comment]
Awesome, thank you so much!

**Comment by durch** [comment]
@floriama #129 adds `BucketCreate` and `BucketDelete`, are there any other ops you need right now, or are we good to ship?

**Comment by floriama** [comment]
Looks good to me! I'll test it as soon as it's merged against b2 and exoscale.
Thanks for the effort!
