### ISSUE TITLE
Setting an Object's ACL's

### ISSUE THREAD

**Issue by Geometrically** [durch/rust-s3#128]
**Is your feature request related to a problem? Please describe.**
I need to set the access level of a file to public when I create it. However, there are no methods to do in the SDK.

**Describe the solution you'd like**
A way to set an object's ACLs (https://developers.digitalocean.com/documentation/spaces/#acls)

**Describe alternatives you've considered**
Nothing yet.

**Comment by Geometrically** [comment]
Nevermind, I figured out you can use the bucket's custom headers

**Comment by durch** [comment]
@Geometrically glad you figured it out, do you maybe have a code snippet we could put in the README to help out folks from the future :)

**Comment by Geometrically** [comment]
```rust
let bucket : Bucket = ...;

bucket.add_header("x-amz-acl", "public-read");
```

This worked for me!

**Comment by durch** [comment]
Rock on! Thank you :)

**Comment by mwnDK1402** [comment]
It was a little hard to find this answer, would be great if this were in the README.

**Comment by Palladinium** [comment]
Note that the workaround does not work with the `put_object_stream` methods, as it adds the custom header to both the initial `CreateMultipartUpload` request (where it's valid), and the final `CompleteMultipartUpload` request, where it's invalid and returns a 400.

It'd be good to have a correct way to set an object ACL's directly while uploading using the streaming methods, but also a way to set object ACLs for existing objects in general (not just during upload).
