### ISSUE TITLE
Support for range in get object

### ISSUE THREAD

**Issue by guilload** [durch/rust-s3#134]
Hello,

I need support for range in get object for a project I'm working on. I'm happy to submit a PR. Do you want me to add a `range: Option<(u64, u64)>` parameter to the `GetObject` command or create a new `GetObjectRange` command? I guess I'd also have to create a new method on the `Bucket` struct called something like `get_object_range`. Shall I also implement the blocking API?

Let me know what you think.

**Comment by durch** [comment]
@guilload that is a good question, I feel like a `GetObjectRange` command is more ergonomic, than another parameter for the `get_object` method family. If its all the same to you I'd go with a new command. I think the only change you'll need to introduce is a conditional header if its the  `GetObjectRange`.  Let me know what you think :)

Blocking API is currently leveraging `tokio` and is only doing a `Runtime::block_on`, I've got a rework of that in progress. There is no need to implement a separate blocking method as these will soon-ish get auto implemented.

**Comment by durch** [comment]
Published to crates.io in `0.27.0-beta0`
