### ISSUE TITLE
Signature mismatch

### ISSUE THREAD

**Issue by jplatte** [durch/rust-s3#144]
**Describe the bug**

When using `bucket.presign_get("/some/path/file.txt")`, I get a signature mismatch with *some* DigitalOcean spaces. The generated presigned URL always contains the slashes in the path encoded as `%2F`, and sometimes this is okay (changing them to `/`es does not break the presigned URL), but sometimes I get a signature mismatch (changing them to `/`es then fixes the presigned URL). I'm not sure whether percent-encoding the path before signing would help, or just make it fail with other servers. Another approach would be to never percent-encode slashes, which all servers seem to support according to the analysis in #133.

**To Reproduce**

I've uploaded an empty file to the S3 space that has this issue. The following presigned URL is valid for 7 days:

https://lumeo-api.sfo2.digitaloceanspaces.com/s3-signing-issue/foo.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=LGYCZBSFXVLMQBZMXVBB%2F20201201%2Fsfo2%2Fs3%2Faws4_request&X-Amz-Date=20201201T114438Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=9ee914bd679aed482b05849bf615a9f8bb39f13ceefd0618c0b014647b78e0db

Here is the same URL, with the `/` before `foo.txt` encoded as `%2F`. You get a signature mismatch when requesting it:

https://lumeo-api.sfo2.digitaloceanspaces.com/s3-signing-issue%2Ffoo.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=LGYCZBSFXVLMQBZMXVBB%2F20201201%2Fsfo2%2Fs3%2Faws4_request&X-Amz-Date=20201201T114438Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=9ee914bd679aed482b05849bf615a9f8bb39f13ceefd0618c0b014647b78e0db

**Expected behavior**

The URL generated by `.presign_get` should work...

**Environment**

 - Rust version: 1.48.0
 - lib version 0.26.3

**Comment by durch** [comment]
@jplatte That might be a path vs subdomain style issue, try instantiating the [bucket with `path_style`](https://docs.rs/rust-s3/0.26.3/s3/bucket/struct.Bucket.html#method.new_with_path_style).

 Due to AWS the default is subdomain style, this will in turn encode all slashes, path style should encode slashes in the path correctly.

**Comment by jplatte** [comment]
Thanks for the fast response!

This is not a path vs subdomain issue, we're already using `path_style`. That I reproduced this with the subdomain style for this bug report is basically just a coincidence.

Should I share a path_style link with the same issue?

**Comment by jplatte** [comment]
I've now also reported this to DigitalOcean, let's see what they say...

**Comment by durch** [comment]
I seem to recall a similar issue a while back, also ended up being with the provider, lets see what they say, I'll be happy to look into this some more. It seems it could be better for sure

**Comment by jplatte** [comment]
I mentioned #133 above, maybe you mean that? I ended up applying a very similar [workaround](https://github.com/lumeohq/rust-s3/commit/383f5f615a99af633ce50172ceecf9d68d6940a2) for now.

**Comment by durch** [comment]
@jplatte root cause here might have been the url encoding issue fixed as part of #148, I'd be interested to hear if it makes your problems go away as well.

**Comment by jplatte** [comment]
That's about `+` though? What the DO support said is that `/` should only be encoded in query parameters, not in the path (though they did not explain why this works on one of their spaces then, I don't really buy this explanation tbh...).

Since the author of #133 didn't find any regressions with not encoding `/` though, how do you feel about no longer encoding it (just in the path)?

**Comment by durch** [comment]
Its actually about all special characters, we were not encoding path correctly at all. As for the slashes, they should not be encoded in the [path](https://github.com/durch/rust-s3/blob/57df3c34595a5d4557cb6f137a32f2a03171644b/s3/src/signing.rs#L72), I've added a [test](https://github.com/durch/rust-s3/blob/683d1c3c7e1569613e67dbb35f757da377020dde/s3/src/signing.rs#L260) for it . We only encode in query string, and signing headers

**Comment by jplatte** [comment]
Are you planning to do a release soon? If not, I can verify this with a git dependency.

**Comment by durch** [comment]
@jplatte fixes from #148 have been published to `0.27.0-beta5`, I'd be happy to help porting any code over, the changes mostly boil down to which features to turn on

**Comment by jplatte** [comment]
Just wanted to test, but 0.27.0-beta5 doesn't compile for me. Opened a new issue about that: #149

**Comment by jplatte** [comment]
> Its actually about all special characters, we were not encoding path correctly at all. As for the slashes, they should not be encoded in the [path](https://github.com/durch/rust-s3/blob/57df3c34595a5d4557cb6f137a32f2a03171644b/s3/src/signing.rs#L72), I've added a [test](https://github.com/durch/rust-s3/blob/683d1c3c7e1569613e67dbb35f757da377020dde/s3/src/signing.rs#L260) for it . We only encode in query string, and signing headers

I've tested with 0.27.0-beta5 and this does not appear to be true. AFAICT, the issue is `Request::url` calling `signing::uri_encode` with `encode_slash` being `true`. I wonder whether that function should ever be encoding slashes, or whether the parameter can just be removed. If it can't, it still seems incorrect to pass `true` in that place.

**Comment by durch** [comment]
It would be ideal to remove it, let me come up with some tests for that, if we can prove its not doing anything useful I'll be happy to take it out!

**Comment by jplatte** [comment]
Ping @durch, any updates on this?

**Comment by durch** [comment]
Unfortunately not @jplatte, got a bit swamped, will do my best to spend time on it this week

**Comment by durch** [comment]
@jplatte That was one long week, hopefully next one is the one :)

**Comment by durch** [comment]
@jplatte just published `0.27.0-beta11` which has a `never-encode-slash` feature which should eliminate the need for any workarounds on your end

**Comment by jplatte** [comment]
Why is it an optional feature rather than the default behaviour?

**Comment by jplatte** [comment]
Finally upgraded to tokio 1.0 and rust-s3 0.27.beta11 with `never-encode-slash`, unfortunately still getting signature mismatch errors.

**Comment by jplatte** [comment]
Went back to my previous fix and that worked again (this time also behind the feature flag): https://github.com/durch/rust-s3/commit/ba26f065f381de057a7922b6006f36b57da71c7a
