### ISSUE TITLE
Use HeaderMap from http crate instead of HashMap for headers

### ISSUE THREAD

**Issue by glebpom** [durch/rust-s3#150]
**Is your feature request related to a problem? Please describe.**
I use minio as a caching storage, along with hyper-based proxy server implementation. I typically use `HeaderMap` struct from `http` crate for manipulating headers. It's used by hyper and support multiple values for the same header name. 

**Describe the solution you'd like**
Use Headers struct from HTTP crate instead of HashMap for storing headers.

**Comment by durch** [comment]
@glebpom Thank you for raising the request, this would be the ideal solution, I've been queuing it up for a while now, will get to it soon-ish :)

**Comment by glebpom** [comment]
Closed by #151
