### ISSUE TITLE
0.27.0-beta6 does not compile with feature flag "with-async-std"

### ISSUE THREAD

**Issue by schoenenberg** [durch/rust-s3#153]
**Describe the bug**
Compile error during compilation of rust-s3 with feature-flag *with-async-std*. 

```
Compiling rust-s3 v0.27.0-beta6
error[E0252]: the name `RequestImpl` is defined multiple times
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-s3-0.27.0-beta6/src/bucket.rs:18:5
   |
16 | use crate::request::Reqwest as RequestImpl;
   |     -------------------------------------- previous import of the type `RequestImpl` here
17 | #[cfg(feature = "with-async-std")]
18 | use crate::surf_request::SurfRequest as RequestImpl;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `RequestImpl` reimported here
   |
   = note: `RequestImpl` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
   |
18 | use crate::surf_request::SurfRequest as OtherRequestImpl;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

...
```

**To Reproduce**
1. New Rust Project
2. Add the following dependencies to `Cargo.toml`
  - `async-std = { version = "1.8.0", features = [] }`
  - `rust-s3 = { version = "0.27.0-beta6", features = ["with-async-std"] }`
3. `cargo build`

**Expected behavior**
Should compile and work.

**Environment**
 - Rust version: 1.48.0
 - lib version: 0.27.0-beta6

**Additional context**
Thanks for implementing support for`async-std` into this crate!

**Comment by durch** [comment]
@schoenenberg you'll also need to disable default features, docs around all these new flags are lacking, apologies. 

```toml
rust-s3 = { version = "0.27.0-beta6", features = ["with-async-std"], default-features = false }
```

should do the trick

**Comment by schoenenberg** [comment]
Thanks, that worked! Are you open for PRs to improve documentation?

**Comment by durch** [comment]
@schoenenberg of course, PRs always welcome :)
