### ISSUE TITLE
0.27 beta9 fails to compile with `blocking` feature

### ISSUE THREAD

**Issue by Ten0** [durch/rust-s3#161]
**To Reproduce**
Steps to reproduce the behavior (ideally with a minimal code sample):
```bash
cargo new tmp
cd tmp
echo 'rust-s3 = { version = "=0.27.0-beta9", features = ["blocking"] }' >> Cargo.toml
cargo check
```

**Expected behavior**
*compiles*

**Actual behaviour**
```
.cargo/registry/src/github.com-1ecc6299db9ec823/rust-s3-0.27.0-beta9/src/bucket.rs:84:63
   |
84 | #[cfg_attr(all(feature = "with-tokio", feature = "blocking"), block_on("tokio"))]
   |                                                               ^^^^^^^^^^^^^^^^^ function or associated item not found in `Runtime`
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rust-s3`
```

**Environment**
 - Rust version: latest stable (`1.49`)
 - lib version `0.27.0beta9`

**Additional context**
- Using feature `blocking`
- Pinning to `0.27.0-beta8` works

**Comment by durch** [comment]
@Ten0 thanks for the report, and apologies for the breakage. I neglected to update `blocking` feature for `tokio` ^1. Published `0.27.0-beta10` that should compile as expected.

**Comment by Ten0** [comment]
Thanks. This seems to work. I think it would be nice to yank the beta9 still, especially considering the way the versions are ranked (that is, alphabetically after the `-`, making `beta10` appear as a lower version than `beta9`, which by the way, is weird and could probably be a cargo/crates issue): https://crates.io/crates/rust-s3/versions

**Comment by durch** [comment]
Oh interesting, I'll yank it now, need to promote this to stable soon anyway :)
