### ISSUE TITLE
aws-creds's `Credentials` initilaized with `from_instance_metadata` are broken after 6 hours.

### ISSUE THREAD

**Issue by Ten0** [durch/rust-s3#163]
**Describe the bug**
aws-creds's `Credentials` initilaized with `from_instance_metadata` are broken after 6 hours, because they expire, as explained here:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

**To Reproduce**
Initialize `Credentials` with `from_instance_metadata`. Wait 6 hours. Attempt an action that requires these credentials to be valid.

**Expected behavior**
*still works*

**Environment**
 - Rust version: latest stable (`1.49`)
 - lib version: aws-creds `0.26.0`

**Solving**
`Credentials` should probably be an structure containing either:
 - constant credentials
 - that they should be fetched from the instance, that the current are *these*, and that they expire at `Expiration`. (`Expiration` is one of the keys returned by the call to `169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`).

In the second case, they should be automatically re-fetched whenever they expire.

**Comment by durch** [comment]
@Ten0 another great catch, I'll look into automatically refreshing these, that is the expected behavior for sure.

**Comment by durch** [comment]
@Ten0 sorry for going AWOL on this, work/life asserted themselves, will try and pick it up next week

**Comment by Ten0** [comment]
No worries, thanks for your dedication :)

**Comment by kennetpostigo** [comment]
Question, does this mean accessing buckets after 6 hours will not work and you will need to re-create and populate the bucket every 6 hours?

**Comment by Ten0** [comment]
Not "bucket" in the sense of "AWS bucket", but `Bucket` in the sense [`aws_s3::Bucket`](https://docs.rs/rust-s3/0.26.4/s3/bucket/struct.Bucket.html). The struct has to be rebuilt, because the credentials stored inside become invalid after 6 hours so it just stops working.

**Comment by Ten0** [comment]
What is this fixed by?

**Comment by durch** [comment]
It wasn't, I have no idea how this got closed, I probably fat fingered it :/
