### ISSUE TITLE
Error Handling in 0.27

### ISSUE THREAD

**Issue by milenkovicm** [durch/rust-s3#164]
**Is your feature request related to a problem? Please describe.**

Handling errors with `0.27` gets much harder as methods are returning anyhow trait. It is a step back from `0.26` which had dedicated error(s). 

As `rust-s3` is a library change to `anyhow`  will make harder for users to handle errors.

**Describe the solution you'd like**

Have you considering exposing `thiserror` instead of `anyhow` ? 
Even `anyhow` documentation says 

> Comparison to thiserror
>
> Use Anyhow if you don't care what error type your functions return, you just want it to be easy. This is common in application code. Use thiserror if you are a library that wants to design your own dedicated error type(s) so that on failures the caller gets exactly the information that you choose

**Describe alternatives you've considered**

Other alternative would be to handle errors yourself but this would make no sense.

**Additional context**

Have no motivation to get into flame wars about library, this is just a suggestion for your consideration.

**Comment by nightmared** [comment]
Hey ! I've being giving this a look today, would you mind tell me what you think of this?
https://github.com/durch/rust-s3/compare/dev...nightmared:thiserror

Also, before opening a PR, I think it would be useful to know if this is a wanted feature (Maybe @durch would prefer keeping `anyhow`?)

As an important note, this is not API compatible with the current 0.27 branch but I guess this is acceptable in a 0.x release.
Also, I fixed the two clippy 1.49 issues (one of them yields code that I actually find less legible that before, but oh well let's not upset clippy!).
finally, I added the sync tests to the Makefile so that it is executed when calling `make ci`.

**Comment by milenkovicm** [comment]
Hi @nightmared, 
it looks good to me but it's up to @durch to decide.

Also, I'd recommend you to split the pr to two commits, one addressing thiserror other addressing clippy

**Comment by durch** [comment]
@milenkovicm, @nightmared thank you both for the discussion, `anyhow` was mostly a spur of the moment decision. There has been a lot of development around error handling, and I'm sort of still stuck in `error_chain` days. I'm very open to a PR or additional discussion as to how we'd want to handle errors in general.

**Comment by milenkovicm** [comment]
@nightmared did a decent job with on this issue in his branch, maybe that could be a good starting point to address this issue.

**Comment by slckl** [comment]
Right now `0.27` feels like a downgrade of sorts with loss of custom error types.
`thiserror` would be strongly preferable to `anyhow` in error handling.

is there maybe something that can be helped with to get #189 over the line?

**Comment by TilBlechschmidt** [comment]
I'd like to add to this that the current use of `anyhow` in `0.27` seems to be broken as well. In the following output I printed the current `anyhow::Error` using `println!("{}")` first and then manually running down the `.cause()` chain.

It seems that on each layer, the previous error has been converted to a string and then embedded into the next error up the chain.

Using `anyhow`'s implementation of `Display`:
```
error sending request for url (http://127.0.0.1:9000/test/test): error trying to connect: tcp connect error: Connection refused (os error 61)

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 61)
    1: tcp connect error: Connection refused (os error 61)
    2: Connection refused (os error 61)
```

Manually iterating the `.cause()` chain:
```
error sending request for url (http://127.0.0.1:9000/test/test): error trying to connect: tcp connect error: Connection refused (os error 61)
---
error trying to connect: tcp connect error: Connection refused (os error 61)
---
tcp connect error: Connection refused (os error 61)
---
Connection refused (os error 61)
```

Overall, I'd definitely agree with the fact that this crate should go with `thiserror` as it allows downstream crates or applications to more easily treat errors and react to them. It then effectively becomes their choice to either ignore, handle, or print the error while the usage of `anyhow` basically makes anything but printing a big headache.

**Comment by durch** [comment]
We've switched to `thiserror` finally :)
