### ISSUE TITLE
Update to tokio 1.0 please?

### ISSUE THREAD

**Issue by rakshith-ravi** [durch/rust-s3#168]
**Is your feature request related to a problem? Please describe.**
I'm not able to compile rust-s3 with tokio 1.0

**Describe the solution you'd like**
Update tokio deps to 1.0 and reqwest to 0.11 please.

**Comment by nightmared** [comment]
Please take a look at the 0.27 beta branch (0.27.0-beta10 (https://crates.io/crates/rust-s3/0.27.0-beta10) does use tokio 1.0).

**Comment by rakshith-ravi** [comment]
Thank you :D

**Comment by rakshith-ravi** [comment]
It would appear that the `rust-s3` crate depends on an older version of `reqwest`, (`v0.10.10`, specifically), which depends on tokio 0.2. If we can just update that to the newer version of reqwest, this issue would be resolved. When I run this right now, it throws an error and panics saying that the reqwest network call wasn't called from the context of a tokio 0.2 runtime, because it was called from the context of a tokio 1.0 runtime. Can we get this fixed too?

**Comment by nightmared** [comment]
The optional dependency of 0.27.0-beta10 is reqwest >=0.11 (per https://crates.io/crates/rust-s3/0.27.0-beta10/dependencies), which relies on tokio 1.0 if I'm not mistaken. Have you tried a recent beta (https://crates.io/crates/rust-s3/versions)?
If it still doesn't work, does your own code have itself a dependency on an old version of reqwest (maybe you have two versions of reqwest coexisting)?
