### ISSUE TITLE
Add an API `put_object_stream_with_content_type`

### ISSUE THREAD

**Issue by chuigda** [durch/rust-s3#172]
**Is your feature request related to a problem? Please describe.**
By this time, `put_object_stream` only supports `octet/stream`, while only non-stream version `put_object_with_content_type` provides utility of setting custom content types.

**Describe the solution you'd like**
I'd like to see a `put_object_stream_with_content_type` added to this repository.

**Describe alternatives you've considered**
None.

**Additional context**
I've read the [AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateMultipartUpload.html) about setting content type when using multi part upload, and made [a small patch](https://github.com/ICEYSELF/rust-s3/commit/a6ce8930a928d5dc5b566f11348c5e9b6d44811e) on the `0.26` branch, in order to satisfy my own requirement.

**Comment by durch** [comment]
@ICEYSELF thanks for submitting this, let me look into that and report back
