### ISSUE TITLE
Is there a way to do a ListBuckets?

### ISSUE THREAD

**Issue by doivosevic** [durch/rust-s3#173]
Hey,
I've been rereading the docs and the source code but I don't get if this is supposed to be supported or not.
I'm wondering if this lib should allow getting https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html
Could you please update the readme with some info about which parts of the S3 api is supported?

**Comment by durch** [comment]
Hi @doivosevic sorry for going MIA on you. Great callout on the ListBuckets method missing. I'll see if I can squeeze that in the next two weeks or so

**Comment by doivosevic** [comment]
It's no rush. I had to switch to rusoto in the meantime because of deadlines but it would be nice if this lib had that feature at some point

**Comment by doivosevic** [comment]
check rusoto. its bare bones wrapper over the s3 api but its really all you
need most of the time

**Comment by doivosevic** [comment]
Also there is now the official library
https://github.com/awslabs/aws-sdk-rust

**Comment by durch** [comment]
Tracked under #251
