### ISSUE TITLE
0.27.0-beta11 is replaced by 0.27.0-beta8 by Cargo due to semver standard comparison

### ISSUE THREAD

**Issue by reasv** [durch/rust-s3#179]
When selecting `rust-s3 = "0.27.0-beta11"` in cargo.toml I noticed my app was panicking, saying tokio 0.2.x was needed.
`beta-11` uses tokio 1.x. But, cargo would automatically install and use `beta8 ` when `beta11` is asked for. This is why it panics.

Current solution is to use `rust-s3 = "=0.27.0-beta11"`

I found out that this is due to semver working with string comparison.
Cargo thinks `beta-8` is more recent than `beta-11` because the strings `beta11` < `beta8`
https://semver.org/#spec-item-11
Solution might be to use `beta.11` or something similar.
If you could release a new version with a new version tag that is detected as higher than `beta-8`, that would solve this issue.

**Comment by reasv** [comment]
https://github.com/reasv/s3test/blob/master/Cargo.toml
Here's a repo that reproduces the problem

**Comment by durch** [comment]
Published `0.27.0-rc1`
