### ISSUE TITLE
0.6.2 contained breaking changes and should be yanked.

### ISSUE THREAD

**Issue by golddranks** [durch/rust-s3#18]
The dependency update published in 0.6.2 contains multiple breaking changes. 0.6.2 should be yanked, and 0.7.0 released instead.

Here are the breaking changes I noticed (there may be others):
* `chrono` 0.2 was updated to 0.4. This breaks the `DateTime` types used in the API of this crate.
* `hmac` and `sha2` both depend on `generic-array`, and they were bumped to 0.8. It seems that even though the API isn't exposed, having `generic-array` 0.7 and 0.8 in the build breaks it. This makes using `rust-s3` together with any crate that depends on `generic-array` 0.7 to break.

**Comment by durch** [comment]
Yanked and pushed 0.7.0, @golddranks thank you for the report, and sorry for the trouble, it was a misstep on my part :(

**Comment by golddranks** [comment]
No problem, thanks for fast support!
