### ISSUE TITLE
GetObjectTorrent API implementation

### ISSUE THREAD

**Issue by vbakc** [durch/rust-s3#181]
**Is your feature request related to a problem? Please describe.**
In S3 documentation there is an endpoint which returns Torrent for an object, but it is currently not implemented by this crate.

**Describe the solution you'd like**
Implement GetObjectTorrent request.

**Describe alternatives you've considered**
Using `rusoto-s3` crate, but I like this crate more.

**Additional context**
![image](https://user-images.githubusercontent.com/30199803/113507530-d0a17b00-9553-11eb-8176-72954cccefba.png)

**Comment by durch** [comment]
@vbakc thanks for raising this, I'll see what I can do, I have some time over the next couple of days :)

**Comment by durch** [comment]
Turned out to be pretty trivial, let me know how if it works as expected. Released as `0.27.0-rc2`

**Comment by vbakc** [comment]
@durch thank you) I'll submit bugs if there are any as soon as we get staging server running
