### ISSUE TITLE
Reuse creation of Client

### ISSUE THREAD

**Issue by Jasperav** [durch/rust-s3#188]
Currently a new Client is created for each time a request is made, e.g.: https://github.com/durch/rust-s3/blob/69e3efe3a7219bc9d2aab8535b74265642e22d45/s3/src/request.rs#L77

The documentation of Client tells us that the Client should be reused: https://github.com/seanmonstar/reqwest/blob/7d8c32784e543b1a2b9536a70db466c0250876c2/src/async_impl/client.rs#L54

It is better for performance to cache. What do you think about this?

**Comment by ahrens** [comment]
I think this relates to (perhaps duplicates?) https://github.com/durch/rust-s3/issues/152.

**Comment by durch** [comment]
Due to the way the request is currently architected, I don't see it happening any time soon
