### ISSUE TITLE
malformed urls in 0.27.0-rc4

### ISSUE THREAD

**Issue by Parth** [durch/rust-s3#196]
# Bug

Our integration tests are failing in `0.27.0-rc4` but not in `0.27.0-rc3`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>MalformedXML</Code>
  <Message>The XML you provided was not well-formed or did not validate against our published schema.</Message>
  <BucketName>d4d571a9-6870-4eb9-8e48-beafa437bddf-1620686849728</BucketName>
  <Resource>/d4d571a9-6870-4eb9-8e48-beafa437bddf-1620686849728</Resource>
  <Region>universe</Region>
  <RequestId>167DD61A6356EF8A</RequestId>
  <HostId>b2db8eab-fe5d-46a2-ae33-2edc190d862b</HostId>
</Error>
```

The `Bucket` was created with `new_with_path_style`, however `d4d571a9-6870-4eb9-8e48-beafa437bddf-1620686849728` is the name of the `Resource` we're trying to `put`, not the name of the bucket.

Downgrading to `0.27.0-rc3` solves this. We're forced to be on 0.27 due requiring `tokio 1.0`.

**Comment by Parth** [comment]
This is also working fine in 0.26

**Comment by durch** [comment]
@Parth this might have been fixed with recent fixes to slash encoding, I'd appreciate another test with 0.30 or 0.31

**Comment by Parth** [comment]
@durch thanks for the heads up, we switched entirely away from S3 for the time being.
