### ISSUE TITLE
Make `get_object_range_blocking` not allocate

### ISSUE THREAD

**Issue by jorgecarleitao** [durch/rust-s3#207]
When calling `get_object_range_blocking` multiple times, we often can re-use `Vec<u8>` between calls. However, the function signature does not allow to pass a buffer to be re-used.

There are at least two ways to handle this:

1. change signature to `get_object_range_blocking<W: std::io::Write>(..., writer: &mut W)`, so that bytes can be written directly to the writer
2. change signature to `get_object_range_blocking(..., writer: &mut Vec<u8>)`, so that bytes can be written directly to an existing `Vec<u8>`.

I think that this is applicable to other methods as well.

**Comment by durch** [comment]
@jorgecarleitao current master has `get_object_range_blocking_to_writer` method which allows for passing in a buffer generic over `Write`
