### ISSUE TITLE
error sending request for url (http://gcb.127.0.0.1:9000/): error trying to connect: dns error

### ISSUE THREAD

**Issue by zhuxiujia** [durch/rust-s3#208]
```error sending request for url (http://gcb.127.0.0.1:9000/): error trying to connect: dns error.```

create  bucket  fail. use ```Bucket::create()``` ( MinIO)

but , use  upload and  download is successful.

**Comment by durch** [comment]
@zhuxiujia Create works if there isn't a bucket already, otherwise it will fail with a 409
