### ISSUE TITLE
get_object should also return the requests headers (content-type, etc) so you don't need to make two requests

### ISSUE THREAD

**Issue by dtzxporter** [durch/rust-s3#213]
**Is your feature request related to a problem? Please describe.**
get_object doesn't return the request information.

**Describe the solution you'd like**
get_object should also return the same as head_object in one request.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by sman908** [comment]
We also would want this to me implemented for obvious reasons.
