### ISSUE TITLE
Rework the API to use facade pattern

### ISSUE THREAD

**Issue by golddranks** [durch/rust-s3#22]
The code of this crate is nicely split up into modules, but each module implementing just one thing, the docs and paths, that is, the outward-facing API is a bit awkward. There isn't a lot of types, so it would make sense to regroup them into larger units, and possibly expose them directly at root.

Facade pattern would help with this: the modules would be private to the crate, and the root module would expose the APIs. This would allow to see the important types at glance in the documentation, plus help with importing stuff; at the moment everything has its own path so it's a bit painful.

Of course, this is a quite big breaking change.

**Comment by durch** [comment]
@golddranks I like the suggestion, I'd have tom dive in the code (and have not been there for some time), but it would be refreshing, maybe aim for a `0.8` or a `0.9` release... Thoughts?
