### ISSUE TITLE
Support OVH S3 Object Storage

### ISSUE THREAD

**Issue by ghost** [durch/rust-s3#232]
**Is your feature request related to a problem? Please describe.**
OVH provides [S3 Object Storage solution](https://www.ovhcloud.com/en/public-cloud/object-storage/), supporting the service would be help us who using the service

**Describe the solution you'd like**
I would like to access OVH S3 storage

**Comment by durch** [comment]
@grubeli this should be a  matter of adding regions only, I've briefly looked at the OVH site and could not find a list of regions, I'd be happy to merge a PR, something along the lines of what was done over [here](https://github.com/durch/rust-s3/pull/235)
