### ISSUE TITLE
Unable to list bucket contents

### ISSUE THREAD

**Issue by thanatos** [durch/rust-s3#24]
I'm attempting to list a bucket contents; however, `Bucket::list` doesn't handle AWS's pagination, so the results are truncated. This seems to be intentional, though as a library consumer, I would really love to not need to implement pagination myself.

However: even aware of this, `Bucket::list` doesn't take a marker for an argument, so there's no good way to get latter pages of data. We can use `add_query`, but this again feels like something that the library should handle more straightforwardly for us. Lastly, even if I use that to provide a marker thusly,

```rust
        let mut bucket = Bucket::new(bucket, region.clone(), credentials.clone());
        if let Some(mark) = marker {
            bucket.add_query("marker", &mark);
        }
        let (list_output, _) = bucket.list("", None)?;
```

I get nonsensical results: `is_truncated` is `true`, but `next_marker` is `None`:

```rust
        if !list_output.is_truncated {
            break;
        } else {
            println!("is_truc = {:?}, marker = {:?}", list_output.is_truncated, list_output.next_marker);
            marker = list_output.next_marker;
        }
```

```
is_truc = true, marker = None
```

After some more digging: `rust-s3` is using `list-type=2`, or v2 of the list API; that version doesn't return a marker, rather, it has been renamed `ContinuationToken`. (I think they did this as there are cases in the v1 API where marker was None, but the response was truncated; you figured out the next marker yourself from the last listed key. Sounds like from the docs they did away with all that; if your response is truncated, you get a continuation token, end of story, which is simpler.)

**Comment by durch** [comment]
@thanatos Thank you for a very detailed report, I've just pushed an update to the `dev` branch, `bucket::list()` now automatically paginates and gets you all results in a `S3Result<Vec<(ListBucketResult, u32)>>`, which you can unpack as:

```rust
let results = bucket.list("", None).unwrap();
for (list, code) in results {
    assert_eq!(200, code);
    println!("{:?}", list.contents.len());
}
```

Each `ListBucketResult` holds a 1000 keys at most.

This will be pushed to Cargo today as `0.8`.

Thanks once again, looking forward to more feedback :)
