### ISSUE TITLE
get_object_stream_blocking requires async

### ISSUE THREAD

**Issue by njaard** [durch/rust-s3#240]
**Describe the bug**
The function `get_object_stream_blocking` is based on `pub async fn get_object_stream<T: AsyncWrite + Send + Unpin, S: AsRef<str>>(&self, path: S, writer: &mut T)`

So when you try to use `get_object_stream_blocking`, the `writer` parameter is still an AsyncWrite. It should be a regular `Write`.

**To Reproduce**
Try to use `get_object_stream_blocking("/", &mut std::io::stdout()).` (compile error)

**Expected behavior**
get_object_stream_blocking should accept a Write.

**Environment**
1.56.1
 - 0.28

**Additional context**
I guess your `block_on` crate should accept overrides for individual functions?

**Comment by durch** [comment]
You're right, this has just changed recently, I'm looking into making it more generic
