### ISSUE TITLE
Why two separate HTTP client libraries?

### ISSUE THREAD

**Issue by jplatte** [durch/rust-s3#243]
When using rust-s3, you pull in two HTTP client libraries: reqwest (from the s3 crate) and attohttpc crate (from aws-creds). Is there a reason these aren't using the same crate?

I'd personally prefer reqwest to be used for both, since that's what other projects we depend on use as well (sendgrid, sentry).

**Comment by durch** [comment]
@jplatte, since `aws-creds` use only sync requests, it pulls `attohttpc` which is lighter. With the right combination of features, `reqwest` does not get pulled at all

**Comment by durch** [comment]
`aws-creds` `attohttpc` has been made an optional dependency
