### ISSUE TITLE
Could not parse HOST header value s3.wasabisys.com

### ISSUE THREAD

**Issue by kallisti5** [durch/rust-s3#255]
**Describe the bug**
Code that was previously working on 0.26 is broken on 0.29.

* s3_endpoint is https://s3.wasabisys.com
* s3_region is us-east-1
* s3_bucket is haiku-repositories-us

**To Reproduce**
```rust

        let region = Region::Custom {
            region: config.s3_region.unwrap(),
            endpoint: config.s3_endpoint.unwrap(),
        };

        let credentials = Credentials::new(config.s3_key.as_deref(), config.s3_secret.as_deref(),
                None, None, None)?;

        // Original:
        let bucket = Bucket::new(&config.s3_bucket.unwrap(), region, credentials)?;
        // Same error:
        let bucket = Bucket::new_with_path_style(&config.s3_bucket.unwrap(), region, credentials)?;


        //let mut architectures: Vec<Architecture> = Vec::new();
        let base_prefix = match config.s3_prefix {
            Some(x) => x,
            None => "".to_string(),
        };

        let results = bucket.list_blocking(base_prefix, None)?;

        let mut routes: Vec<Route> = Vec::new();
        for (list, code) in results {
            if code != 200 {
                return Err(From::from(format!("HTTP {} from S3!", code)));
            }
```

Result with
  ```let bucket = Bucket::new(&config.s3_bucket.unwrap(), region, credentials)?;```

```Could not parse HOST header value s3.wasabisys.com```

Result with
 ```let bucket = Bucket::new_with_path_style(&config.s3_bucket.unwrap(), region, credentials)?;```
 
```
Could not parse HOST header value haiku-repositories-us
.s3.wasabisys.com
```

from bucket.list_blocking above.

**Expected behavior**
Functional

**Additional context**

**Comment by kallisti5** [comment]
This was a bug on our side.  We weren't sanitizing the inputs well enough and each String had a newline at the end of it which seems to *really* piss off rust-s3 0.29 :-)

Resolved on our end... however maybe the crate should sanitize inputs too?

**Comment by durch** [comment]
Thats a good idea, I'll look into it for sure
