### ISSUE TITLE
Implement loading credentials from profiles

### ISSUE THREAD

**Issue by Phrohdoh** [durch/rust-s3#26]
https://github.com/durch/rust-s3/blob/2f684e28b8750fb9b5ea44572c95935d918d73f7/src/credentials.rs#L11-L13

**Comment by durch** [comment]
@Phrohdoh thanks for the kick, version `0.9` pushed to [crates.io](https://crates.io/crates/rust-s3)

**Comment by Phrohdoh** [comment]
Awesome, thank you so much! 😄
