### ISSUE TITLE
is there any plan to reuse the reqwest client?

### ISSUE THREAD

**Issue by ggslayer** [durch/rust-s3#261]
It's too bad for me that the dns requery when every http request if not resue the reqwest client, and http tcp connect every time is waste.

I want to know if there is time plan to reuse the reqwest client?  Thank you very much!

Or if there is no plan , please give me some advise to modify the code, and i will write and test it myself.  thankyou very much!

**Comment by durch** [comment]
@ggslayer I don't have any plans at the moment, I'll be very happy to review a PR, as long as it does not make the API a hassle, we can probably get away with passing an optional client argument to Bucket or bucket methods. Keep in mind that it also needs to work for `async-std` which does not use `reqwest`
