### ISSUE TITLE
add support the `cors` api

### ISSUE THREAD

**Issue by attila-lin** [durch/rust-s3#263]
**Is your feature request related to a problem? Please describe.**

the api with put/get/delete bucket cors.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[PutBucketCor](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketCors.html)
[GetBucketCors](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketCors.html)
[DeleteBucketCors](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteBucketCors.html)

**Comment by durch** [comment]
Added in `0.36.0-beta.1`
