### ISSUE TITLE
default Bucket::request_timeout too low, or shouldn't be based on full transfer time

### ISSUE THREAD

**Issue by njaard** [durch/rust-s3#264]
**Describe the bug**
When doing a `Bucket::get_object_stream`, if the file is very large, it will exceed the `request_timeout` and the download will fail.

I think this behavior violates the principle of least surprise; right now rust-s3 simply cannot be used by default on large files or slow or high-latency connections.

**To Reproduce**
```
let b = s3::bucket::Bucket::new(...).unwrap();
b.get_object_stream("path to a file larger than about 1GB on a reasonably fast connection", &mut writer);
```

This command will fail with `TimedOut`.

**Expected behavior**
By default, rust-s3 should allow one to download any sized file with the default settings.

**Environment**
 - Rust version: 1.59
 - lib version 0.30
 - "sync" feature enabled

**Additional context**
I think there should be no default timeout of the "entire request" kind, i don't think the class of error it can prevent is worse than the problem I experienced.

A more useful timeout that could be enabled by default would be "time to first byte".

Furthermore, documentation says the default timeout is 30 seconds, but the actual default timeout is 60 seconds according to the code. This tells me you found 30 seconds was too low at some point :)

Finally, thank you for the work you've put into this crate, it's very useful and you've done a great job!

**Comment by durch** [comment]
@njaard I'm not sure how to address the issue, other then with a timeout, and since timeouts must exist there has to be a default. Since the timeout is in the underlaying implementation of HTTP clients used. Timeout for a bucket can be changed with a method, or at creation (since 0.31). I think I remember that in the days of yore the default timeout was `None`, which could cause the request to just hang forever, so a sensible timeout was chosen instead. 

The 95% use case seems to be some sort of a timeout, and if you have a suggestion for a more ergonomic default or a mroe graceful handling of these issues I'd be happy to oblige :)

**Comment by njaard** [comment]
I think a more ergonomic default is "30 second connection timeout and unbound download timeout".

I think it's unfortunate that hyper has a timeout, and it appears that you're just following its lead, so I conducted a survey of other http libraries:

# Has no default timeout on total transmission
* curl
* python's urllib
* Go's http client
* Java, 5 minute connection or inter-packet timeout, but not transfer time
* firefox, 90 second _connection_ timeout

# Has a default timeout
* rust's reqwest
* C# (but there's the chance it's just time to connection or inter-packet time, I can't tell from documentation)

I think a more ergonomic default is: 60 second connection timeout and no transfer timeout, and then as a secondary feature, a 60 second time-to-next-packet timeout. Right now, an 8 GB file simply cannot be downloaded over a typical 1GBit connection by default, which I would call "pathological"; you could keep on increasing the timeout until you realize that the measure itself has no value.

**Comment by njaard** [comment]
Well, obviously this is a problem for upstream, for example: https://github.com/seanmonstar/reqwest/issues/870 so I'll close this ticket with my thanks!

**Comment by durch** [comment]
Thank you, I love a good discussion :)

**Comment by durch** [comment]
I’ve been actually thinking about moving away for reqwest, if there are other tokio compatible libs out there I’d be happy to give them a whirl
