### ISSUE TITLE
Error: SerdeXml(Custom { field: "missing field `Name`" }) with MinIO

### ISSUE THREAD

**Issue by gsollazzo** [durch/rust-s3#269]
**Describe the bug**
When running this minimal MinIO example (taken from [https://github.com/durch/rust-s3/blob/master/s3/bin/simple_crud.rs]( https://github.com/durch/rust-s3/blob/master/s3/bin/simple_crud.rs) with some adaptions due to deprecated functions), the listing fails with ``"Error: SerdeXml(Custom { field: "missing field `Name`" })"``

No requests are logged from MinIO "Watch" console.

**To Reproduce**

```rust
extern crate s3;

use s3::bucket::Bucket;
use s3::creds::Credentials;
use s3::region::Region;
use s3::error::S3Error;

struct Storage {
    name: String,
    region: Region,
    credentials: Credentials,
    bucket: String,
    location_supported: bool,
}

fn main() -> Result<(), S3Error> {

    let minio = Storage {
        name: "minio".into(),
        region: Region::Custom {
            region: "".into(),
            endpoint: "http://127.0.0.1:9000".into(),
        },
        credentials: Credentials {
             access_key: Some("ACCESSKEY".to_owned()),
             secret_key: Some("SECRETKEY".to_owned()),
             security_token: None,
             session_token: None,
        },
        bucket: "data".to_string(),
        location_supported: false,
    };

    
    let bucket = Bucket::new(&minio.bucket, minio.region, minio.credentials)?.with_path_style();

    let results = bucket.list_blocking("".to_string(), None)?;
    
        for result in results {
            println!("{:?}", result);
        }

        Ok(())

}
```

**Expected behavior**
I would expect to send a query to MinIO and to print some results (the bucket has files).

**Environment**
WSL-2 with Ubuntu.

```toml
[package]
name = "s3test"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-s3 = { version = "0.31.0", features = ["blocking"] }
```

**Comment by anomalyze** [comment]
Just FYI, i had this exact same issue with an S3 bucket. I didn't actually require the feature, so i stopped debugging it sorry.

**Comment by wesin** [comment]
anyone who want find some solution, may can use 0.27.0, it seems the lastest sdk can not work with minio.

**Comment by grizwako** [comment]
Hey, same issue with S3 bucket, running on 0.29.

Bug is not reproducible, every now and then `list_blocking()` fails.

```
Error: listing entries at prefix/2077/11/25/

Caused by:
    0: serde xml: custom: missing field `Name`
    1: custom: missing field `Name`
```

**Comment by Tails** [comment]
Same issue on v0.31 when using sync list() with Filebase as S3 provider.

**Comment by Tails** [comment]
It actually gives you the error when you parse the bytes to a string:

```rust
if let Ok((data, code)) = res {
        let s =  String::from_utf8(data).unwrap();

        dbg!(s);

        assert_eq!(code, 200);
    }
    
    // <?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>e4c5b62f-86e2-4690-aa38-8b250e238412</RequestId><HostId>ZmlsZWJhc2UGQ0NC1scjRxbA==</HostId></Error>"
```

Of course such a response does not contain the expected field. However, authorization errors should be handled by the library itself. Maybea HTTP status code is returned by the S3 server that is not accounted for, 404 in my case.

**Comment by durch** [comment]
Errors do need a revamp, I'll have some time in the next few days, will take a look

**Comment by Tails** [comment]
@durch thank you for your beautiful code! Had a look today and was impressed.

**Comment by durch** [comment]
This is caused by the `fail-on-err` feature, or rather lack of it, by default we allow everything through, regardless of the response code, I've been thinking on it for a while now, and it probably makes sense to have that as a default feature, principle of least surprise, I'll make it default in `0.32.0`

**Comment by DavidVentura** [comment]
I've just hit this as well, turns out I needed to call `with_path_style()` on the `Bucket` object
