### ISSUE TITLE
Connecting to Cloudflare R2 - get "Unauthorized" with presign get and put

### ISSUE THREAD

**Issue by KavikaPalletenne** [durch/rust-s3#271]
I am trying to connect to my R2 bucket with the rust_s3 package. However, the presigned put and get URLs come up as “Unauthorized” when using then. Is there something wrong with my setup? I am not sure if I am using the correct keys for access and secret key. These keys work when using S3 SDK for JavaScript.

```rust
let credentials = Credentials::new(
        Option::from(<Cloudflare R2 Access Key Id>), // access_key
        Option::from(<Cloudflare R2 Secret Access Key>), // secret_key
        None,
        None,
        None,
    )
    .unwrap();

    let region = Region::Custom {
        region: "us-east-1",
        endpoint: "https://<accountid>.r2.cloudflarestorage.com",
    };

    Bucket::new(<bucket_name>, region, credentials)
        .unwrap()
        .with_path_style()
```

**Comment by durch** [comment]
I've still not tested against R2, I've requested beta access a while ago, and never got it. Now that its open access I'll give it a go again

**Comment by KavikaPalletenne** [comment]
When I was using R2, they did not support presigned URLs. But looking at the forums now, it seems they have added that functionality.

**Comment by durch** [comment]
There is now a test for R2, and an entry in the `Region` enum, closing
