### ISSUE TITLE
Get stream API

### ISSUE THREAD

**Issue by mihaigalos** [durch/rust-s3#275]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Using the `async` flavor, would like to have an API call to get a stream object (implementing trait `futures_core::stream::Stream`) for `GET`/`PUT` a file to a bucket.
This will then be used in a loop to write/read to/from a file and update a progress bar.

**Describe alternatives you've considered**
Alternatively, provide an API call to a observable callback with the current progress (percentage or transferred bytes), which clients can dependency-inject during `Bucket::new()`.
The callback would be called during io operations with the bucket.
Other suggestions are welcome.

**Additional context**
Consider the following code. This is how I would consume the stream for a `GET`. Similar for a `PUT`.

<details>
  <summary>Click to expand!</summary>

```rust
async fn get(input: &str, output: &str, bar: &mut WrappedBar) -> Result<(), ValidateError> {
    let parsed_address = ParsedAddress::parse_address(input, bar.silent);
    let (mut out, mut downloaded) = io::get_output(output, bar.silent);

    let res = reqwest::Client::new()
        .get(input)
        .header("Range", "bytes=".to_owned() + &downloaded.to_string() + "-")
        .header(
            reqwest::header::USER_AGENT,
            reqwest::header::HeaderValue::from_static(CLIENT_ID),
        )
        .basic_auth(parsed_address.username, Some(parsed_address.password))
        .send()
        .await
        .or(Err(format!("Failed to GET from {} to {}", &input, &output)))
        .unwrap();
    let total_size = downloaded + res.content_length().or(Some(0)).unwrap();

    bar.set_length(total_size);

    let mut stream = res.bytes_stream();
    while let Some(item) = stream.next().await {
        let chunk = item.or(Err(format!("Error while downloading."))).unwrap();
        out.write_all(&chunk)
            .or(Err(format!("Error while writing to output.")))
            .unwrap();
        let new = min(downloaded + (chunk.len() as u64), total_size);
        downloaded = new;
        bar.set_position(new);
    }

    bar.finish_download(&input, &output);
    Ok(())
}
```
</details>

**Comment by durch** [comment]
As of `0.33.0-beta1` `get_object_stream` returns a `ResponseDataStream`, which has a `bytes()` method that is `Stream<Item = Bytes>`, I'd appreciate if you could test it out. I expect tokio backend works much better then async-std for tnis

**Comment by mihaigalos** [comment]
This is awesome. I have an API breaking change where I'm consuming this crate now and would need to first onboard the newest version first.

**Comment by durch** [comment]
Glad you like it, let me know if/when you get to it :)

**Comment by netthier** [comment]
@durch I'm trying to use this new API together with axum's `StreamBody` which requires the Stream to be `Send`.
Is there a reason the ResponseDataStream isn't?

**Comment by mihaigalos** [comment]
I had a look, @durch. I reconciled most of my errors. This one I don't understand:

I'm using `get_object_stream()` as in the [docs](https://docs.rs/rust-s3/latest/s3/bucket/struct.Bucket.html#method.get_object_stream):
```rust
let response_data_stream = bucket.get_object_stream(input);
while let Some(chunk) = response_data_stream.bytes().next().await {
     async_output_file.write_all(&chunk).await?;
}
```
Which produces:
```bash
error[E0599]: no method named `bytes` found for opaque type `impl futures_util::Future<Output = Result<ResponseDataStream, S3Error>>` in the current scope
  --> src/s3.rs:65:54                                                                                     
   |                  
65 |         while let Some(chunk) = response_data_stream.bytes().next().await {
   |                                                      ^^^^^ method not found in `impl futures_util::Future<Output = Result<ResponseDataStream, S3Error>>`
                                                                                                                                                                                                                     
error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
  --> src/s3.rs:65:24                                                                                     
   |                                 
65 |         while let Some(chunk) = response_data_stream.bytes().next().await {                                                                                                                                     
   |                        ^^^^^ doesn't have a size known at compile-time
   |                      
   = help: the trait `Sized` is not implemented for `[u8]`
   = note: all local variables must have a statically known size
   = help: unsized locals are gated as an unstable feature
```

If you're interested, [here](https://docs.rs/rust-s3/latest/s3/bucket/struct.Bucket.html#method.get_object_stream) are the lines in code.

**Comment by durch** [comment]
@netthier not sure which version you tried this with, try either 0.33, or 0.34-beta*, `ResponseDataStream` should be `Send` -> https://docs.rs/rust-s3/latest/s3/request/request_trait/struct.ResponseDataStream.html

**Comment by mihaigalos** [comment]
Hi @durch, I've gotten rid of most of the compilation errors owing to the the API change.
I'm now faced with one I don't understand.

I'm using `get_object_stream()` form from the [docs](https://docs.rs/rust-s3/latest/s3/bucket/struct.Bucket.html#method.get_object_stream):

```rust
async fn _get(input: &str, output: &str, bar: &mut WrappedBar) -> Result<(), HTTPHeaderError> {
    let (path, bucket) = S3::setup(input, bar.silent).await;
    let mut async_output_file = tokio::fs::File::create(output) //TODO: when s3 provider crate has stream support implementing futures_core::stream::Stream used in resume, use io.rs::get_output() instead.
        .await
        .expect("Unable to open output file");
    
    let mut response_data_stream = bucket.get_object_stream(path).await.unwrap();

    while let Some(chunk) = response_data_stream.bytes().next().await {
        async_output_file.write_all(&chunk).await.unwrap();
    }

    Ok(())
}
```
Which produces:
```
error: future cannot be sent between threads safely
   --> src/driver.rs:112:60
    |
112 |             Box::new(move |a: &_, b: &_, c: &mut _, d: &_| crate::s3::S3::get(a, b, c, d).boxed()),
    |                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ future returned by `get` is not `Send`
    |
    = help: the trait `std::marker::Send` is not implemented for `(dyn futures_util::Stream<Item = bytes::bytes::Bytes> + 'static)`
note: future is not `Send` as this value is used across an await
   --> src/s3.rs:66:68
    |
64  |         let mut response_data_stream = bucket.get_object_stream(path).await.unwrap();
    |             ------------------------ has type `ResponseDataStream` which is not `Send`
65  |
66  |         while let Some(chunk) = response_data_stream.bytes().next().await {
    |                                                                    ^^^^^^ await occurs here, with `mut response_data_stream` maybe used later
...
72  |     }
    |     - `mut response_data_stream` is later dropped here
note: required by a bound in `futures_util::FutureExt::boxed`
   --> /home/mihai/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.28/src/future/future/mod.rs:520:23
    |
520 |         Self: Sized + Send + 'a,
    |                       ^^^^ required by this bound in `futures_util::FutureExt::boxed`
```

If you want to have a look at the code, I've pushed it [here](https://github.com/mihaigalos/aim/pull/255/files#diff-3f5d73c0a7fa3d77471a41643c10374ecdb5b779a4ee5135be71eb2fdbaaae4fL55).

**Comment by mihaigalos** [comment]
In the meantime, I'll be using `get_object_to_writer()`.

I still don't understand the error above, though.

**Comment by netthier** [comment]
> @netthier not sure which version you tried this with, try either 0.33, or 0.34-beta*, `ResponseDataStream` should be `Send` -> https://docs.rs/rust-s3/latest/s3/request/request_trait/struct.ResponseDataStream.html

Ah, I tried with 0.33 at the time where `ResponseDataStream` is `!Send`:
![grafik](https://user-images.githubusercontent.com/66856670/230771762-538225f5-f5e0-4dc8-9e76-b0d24212186d.png)
https://docs.rs/rust-s3/0.33.0/s3/request/request_trait/struct.ResponseDataStream.html#impl-Send-for-ResponseDataStream

Since 0.33 is also the latest stable version, the link you provided also shows that `!Send` impl.

**Comment by durch** [comment]
Oh wow, not sure how I managed to not see the freaking `!`, anyway will look into it not sure why its not `Send`

**Comment by netthier** [comment]
It seems to be Send in 0.34

**Comment by durch** [comment]
Yes! Just figured out why I'm not crazy, yeah, I knew it was send :D
