### ISSUE TITLE
Regression: Can't obtain file body as Vec<u8> without reallocating since "Proper response type"

### ISSUE THREAD

**Issue by Ten0** [durch/rust-s3#280]
**Is your feature request related to a problem? Please describe.**
Since https://github.com/durch/rust-s3/commit/0484173489335ad2563dcbd43c269c4fd8275ce1 we can only access the file body as a slice in `ResponseData`.
This requires reallocating the entire file contents if needing to return it as a `Vec<u8>` (for backend-agnostic interface).

**Describe the solution you'd like**
```rust
impl ResponseData {
    fn into_bytes(self) -> Vec<u8> {
        self.bytes
    }
}
```

**Additional context**
This is an regression encountered when updating from 0.31 to 0.32.

**Comment by durch** [comment]
Version `0.32.3` provide Into<Vec<u8>> for ResponseData
