### ISSUE TITLE
Presigned links broken as of 0.32

### ISSUE THREAD

**Issue by Ten0** [durch/rust-s3#283]
**Describe the bug**
Presigned links are deemed invalid by AWS as of version 0.32.
They worked fine in version 0.31.

**To Reproduce**
Generate a presigned link in 0.32.
See the following error message back from AWS:
```xml
<Error>
<Code>InvalidToken</Code>
<Message>
The provided token is malformed or otherwise invalid.
</Message>
```

**Expected behavior**
*works*

**Environment**
 - Rust version: latest stable
 - lib version: `0.32.1`

**Additional context**

Looks like at least the `X-Amz-Security-Token` variable is not properly urlencoded in 0.32, while it does get properly urlencoded in previous versions.

**Comment by Ten0** [comment]
This would be the culprit:
https://github.com/durch/rust-s3/commit/530e0c27cf781ed20fed41ee82dc044821499a87#diff-fe2e216f9675ca137d41284ea89c484ba7b74ecae726ba79119e6a8f50346b96

**Comment by Ten0** [comment]
Shouldn't we also make a release and yank the corresponding versions?

**Comment by durch** [comment]
We should, and we will :)
