### ISSUE TITLE
Please implement From<ResponseData> for Vec<u8>

### ISSUE THREAD

**Issue by msrd0** [durch/rust-s3#288]
**Describe the bug**
There's an implementation `Into<Vec<u8>>` for `ResponseData`. This means that when Rust can't infer a type, we need to use `<ResponseData as Into<Vec<u8>>>::into(data)`. If there was a `From` impl instead, the `Into` implementation would still be provided but we can write `Vec::from(data)` which is much cleaner.

Probably related to #280

**Environment**
 - Rust version: `1.62.1`
 - lib version: `0.32.3`

**Comment by durch** [comment]
@msrd0 this is a valid suggestion, the reason I went with `Into` is that `ResponseData` also has a `status_code` field. So a `From<Vec<u8>>` can't work without introducing ambiguity around the `status_code` field. Open to suggestions around handling it

**Comment by msrd0** [comment]
No, I don't mean `From<Vec<u8>> for ResponseData` but `From<ResponseData> for Vec<u8>`. The current `Into` implementation is then provided by the blanket impl in `std`.

**Comment by durch** [comment]
Oh, I see what you're saying, you're absolutely right, will be pushed out in the next release
