### ISSUE TITLE
Obvious put object bug

### ISSUE THREAD

**Issue by szguoxz** [durch/rust-s3#289]
It's obvious just by looking at the source code in bucket.cs:

 async fn _put_object_stream_with_content_type<R: AsyncRead + Unpin>(
        &self,
        reader: &mut R,
        s3_path: &str,
        content_type: &str,
    ) -> Result<u16, S3Error> {
        // If the file is smaller CHUNK_SIZE, just do a regular upload.
        // Otherwise perform a multi-part upload.
        let first_chunk = crate::utils::read_chunk(reader).await?;
        if first_chunk.len() < CHUNK_SIZE {
###             **We forgot the content type here when calling self.put_object**
            if response_data.status_code() >= 300 {
                return Err(error_from_response_data(response_data)?);
            }
            return Ok(response_data.status_code());
        }

**Comment by durch** [comment]
@szguoxz I'm not sure what you're getting at, the content-type of the put_object is always `application/octet-stream`, could you please provide an error message, or a snippet that we can reproduce.

**Comment by szguoxz** [comment]
buddy, there's no error message. :-)
this put_object is called inside: _put_object_stream_with_content_type, so when you call put_object, you need to carry the content type along. Of course, you actually need to use a different function.

**Comment by durch** [comment]
Oh wow, I see what you're saying, great catch
