### ISSUE TITLE
Support alternate S3 endpoints

### ISSUE THREAD

**Issue by mbeattie** [durch/rust-s3#29]
It would be nice to be able to feed it a custom URL for the S3 endpoint. That way this could be pointed at something like Ceph or Cleversafe.

The way it is now, I need to edit the region.rs and add custom endpoints there that get referenced via region.

**Comment by durch** [comment]
@mbeattie a `Custom(String)` field to the `Region` enum, you can pass in the fully qualified endpoint there and it should work for any arbitrary URL. Like for #30 did not test so all feedback is very appreciated, its available in `0.10.0-beta.0`:

```
[dependencies]
rust-s3 = {version = "0.10.0-beta.0"}
```
