### ISSUE TITLE
S3 pre-signed url for a multipart upload part

### ISSUE THREAD

**Issue by michaelmenon** [durch/rust-s3#293]
Is there any way to get pre-signed url for an s3 object for a multipart upload given part id and upload id ? Looked at the docs but could not find any thing. Any suggestion or help would be great.

**Comment by durch** [comment]
I'm not sure, I think multipart upload is only an implementation detail, uploaded file is transparently assembled on S3 side. For example if you upload a file that would benefit from multipart upload, library will do it for you automatically...

**Comment by Star3Lord** [comment]
I upload(PUT) the file on frontend but all other interaction with S3 goes through backend (initiating, completing, aborting). Server returns pre-signed urls which the browser just uploads to directly so file data doesn't have to go through the server. I am migrating my api server from python to rust and realized that rust-s3 doesn't have method to generate pre-signed urls for chunks in multipart upload which is commonly used in practice where frontend is involved. Please consider adding this feature.
