### ISSUE TITLE
Allow disable of ssl verification

### ISSUE THREAD

**Issue by mbeattie** [durch/rust-s3#30]
It would be nice to be able to disable SSL verification. There are situations in an internal corporate environment with proxies or alternate S3 implementations that either perform MITM attacks or just have self signed certificates and it would be nice to have an option to just blindly accept these scenarios.

My current solution is a monkey patch on request.rs to add `handle.ssl_verify_peer(false);` to the execute function.

**Comment by durch** [comment]
@mbeattie added a `no-verify-ssl` feature flag, you can get the `beta` version and try it out. I did not yet have a chance to test this, so feedback would be very useful :). Just add the `beta` version to your dependancies:

```
[dependencies]
rust-s3 = {version = "0.10.0-beta.0", features = ["no-verify-ssl"]}
```
