### ISSUE TITLE
*_with_content_type functions not setting content type on S3

### ISSUE THREAD

**Issue by Qwertie-** [durch/rust-s3#312]
**Describe the bug**
It seems that the put_object_with_content_type and put_object_stream_with_content_type methods are not setting the content type for uploaded objects on S3

**To Reproduce**
A minimal test which shows the issue

```
use s3::{bucket::Bucket, creds::Credentials};
use tokio::fs::File;
#[tokio::main]
async fn main() {
    let mut file = File::open("/path/to/image.jpg")
        .await
        .unwrap();
    let region: s3::Region = "us-west-2".parse().unwrap();
    let credentials = Credentials::default().unwrap();
    let bucket = Bucket::new("bucket-name", region, credentials).unwrap();
    let content_type = "image/jpeg";

    bucket
        .put_object_stream_with_content_type(&mut file, "test/file2", content_type)
        .await;
}
```

**Expected behavior**
I would expect this to show image/jpeg on the AWS web ui but instead it shows
<img width="1080" alt="Screenshot 2022-11-09 at 09 24 35" src="https://user-images.githubusercontent.com/6601505/200693691-218cb67c-c712-4854-bff4-30b47f7c12c9.png">

**Environment**
 - Rust version: rustc 1.64.0 (a55dd71d5 2022-09-19)
 - lib version 0.32.3

**Comment by durch** [comment]
I believe this was fixed at some point in the past two years, please reopen if still an issue
