### ISSUE TITLE
bug: Potential regression with Bucket Creation in 0.32.3

### ISSUE THREAD

**Issue by No9** [durch/rust-s3#322]
Hi All 
Thanks for building this awesome library!! 
If you have a minute it would be great to get your opinion on this issue.

**Describe the bug**
We have upgraded our application from 0.31 to 0.32.3 and there seems to be an issue with the creation of bucket objects when using AWS. It seems to work in other s3 compatible storage but AWS is the issue.
https://github.com/IBM/core-dump-handler/issues/126 

**To Reproduce**
This is the bucket creation code that used to work but now fails
https://github.com/IBM/core-dump-handler/blob/ac737112fb6d2ba046942befb226c1f645f56d33/core-dump-agent/src/main.rs#L353-L394 
Apart from the library change nothing else has changed with that code.

**Expected behavior**
Creation of bucket object should work.

**Environment**
 - Rust version: 1.66
 - lib version 0.32.3

**Additional context**
We are going to downgrade the version of the library to the last working version 0.31 to make sure the issue we have identified the cause and report back

**Comment by durch** [comment]
@No9 very interesting, I don't think I've touched bucket creation code in a long while, did you maybe manage to collect more details?

**Comment by durch** [comment]
@No9 closing for now, please reopen if it is still an issue
