### ISSUE TITLE
AWS_ENDPOINT and AWS_REGION env support

### ISSUE THREAD

**Issue by jpds** [durch/rust-s3#325]
**Is your feature request related to a problem? Please describe.**

Please add support for `AWS_ENDPOINT` and `AWS_REGION`/`AWS_DEFAULT_REGION` environment variables - this is useful for interacting with S3 endpoints that are not-hosted at AWS itself.

**Comment by durch** [comment]
Something like [this](https://github.com/durch/rust-s3/commit/f46eda9bba80cc8b0912114075837de5b9b76fc0)? Will be released in the next 0.34.0-beta
