### ISSUE TITLE
`make ci` failing due to `Credentials::default` implementation

### ISSUE THREAD

**Issue by joaommartins** [durch/rust-s3#327]
**Describe the bug**
`make ci` fails on master branch due to clippy error on Credentials::default implementation.

**To Reproduce**
`make ci`

**Expected behavior**
`make ci` passes without skipping clippy check, by implementing the `std::default::Default` trait instead of a member function as it is currently.

**Environment**
 - Rust version: [e.g. `1.62`]
 - lib version [e.g. `0.34`]

**Additional context**
This is a simple issue to fix, but the `std::default::Default` trait `default()` return is different to the current `Credentials::default`. Changing the return type creates the need to update all the usage of Credentials::default, as well as all the documentation and examples.

**Comment by durch** [comment]
@joaommartins thanks for raising, fixed
