### ISSUE TITLE
#299 introduces a regression that breaks rustls + tokio support

### ISSUE THREAD

**Issue by ryanswrt** [durch/rust-s3#336]
**Describe the bug**
Previously the `with-tokio` feature could be used with `tokio-rustls-tls` - allowing for easy static compilation with musl. After #299 was merged, `with-tokio` will always pull in `native-tls`; which forces an openssl dependency

**To Reproduce**
Upgrade from 0.33.0 to 0.34.0-beta2 with only the  `with-tokio` and `tokio-rusttls-tls` features enabled, and you will no longer be able to compile with musl 

**Expected behavior**
`rusttls` to be used

**Comment by lpotthast** [comment]
Ran into the same issue. This is still an issue with the latest `beta3` release.

**Comment by durch** [comment]
Fixed as of 0.35 at least
