### ISSUE TITLE
S3 Presigned Post url

### ISSUE THREAD

**Issue by joelawm** [durch/rust-s3#339]
While Trying to implement the example in [Post](https://docs.rs/rust-s3/latest/s3/bucket/struct.Bucket.html#method.presign_post) I get a `internal error: entered unreachable code` in request\request_trait.rs:200:18

**To Reproduce**
Try and use the example

**Expected behavior**
I'm not sure if it s a oversite or not officially supported.

**Environment**
 - Rust version: 1.68.2
 - lib version 0.33.0

**Comment by cs-clarence** [comment]
any updates on this? I've also encountered this

**Comment by joelawm** [comment]
Yea @cs-clarence so to get around this I just implemented a lambda function in AWS Node till #358 gets resolved and/or in the official aws-sdk-rust [Issue 863](https://github.com/awslabs/aws-sdk-rust/issues/863) gets added. There really isn't a way around this unfortunately!
