### ISSUE TITLE
is there a way to get the region from the bucket instead of passing it.

### ISSUE THREAD

**Issue by infinite-Joy** [durch/rust-s3#35]
aws has an implementation

    aws s3api get-bucket-location --bucket <bucketname>

**Comment by durch** [comment]
@infinite-Joy great request, should be implemented in a day or two :)

**Comment by durch** [comment]
Seems like I spoke too soon, in order to authorise the request the region must be know, one thing I'm considering doing is brute-forcing a region, however that is not really ergonomic or friendly :/
