### ISSUE TITLE
Feature request: No verify SSL should be a parameter rather than a feature

### ISSUE THREAD

**Issue by mdecimus** [durch/rust-s3#379]
Hi,

I would like to propose specifying `no_verify_ssl` as a function parameter rather than a crate feature:

https://github.com/durch/rust-s3/blob/5105a1bff57827f88fb90840f03193665ea34d68/s3/src/request/tokio_backend.rs#L31

We interact with different object stores, some of them have valid certificates while others have self-signed certificates. Currently we need to disable TLS verification for all hosts in order to be able to support both self-signed and valid certificates.

**Comment by durch** [comment]
Gets tricky since we have to support three different runtimes with their respective clients, but I do feel the pain here, thinking off a way to make it nice

**Comment by durch** [comment]
[Added in `0.36.0-alpha.3](https://docs.rs/rust-s3/0.36.0-alpha.3/s3/bucket/struct.Bucket.html#method.set_dangereous_config)

**Comment by mdecimus** [comment]
Thanks!
