### ISSUE TITLE
RUSTSEC-2024-0336: DoS in rustls: Infinite loop based on network input

### ISSUE THREAD

**Issue by bowlofeggs** [durch/rust-s3#385]
The current release of rust-s3 uses `rustls 0.20` via `attohttpc`. Unfortunately, the fixes for [RUSTSEC-2024-0336](https://rustsec.org/advisories/RUSTSEC-2024-0336) start in the `0.21` series. This means that users of the stable version of `rust-s3` are unable to update `rustls` to address this issue.

It looks like the release candidates for `rust-s3` allow newer versions of `rust-s3` to be used. Is it possible to make a release to address this?

**Comment by durch** [comment]
`0.34` brings in rustls 0.21
