### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by Plawn** [durch/rust-s3#398]
**Is your feature request related to a problem? Please describe.**
I'm running behind a corporate proxy and crates such as reqwest automatically use the system proxy, maybe this crate could do the same or at least let the user specify a proxy

**Describe the solution you'd like**
use hyper_proxy: https://docs.rs/hyper-proxy/latest/hyper_proxy/ to set the proxy for the http client

Thanks !

**Comment by durch** [comment]
Moved away from using raw hyper, not sure what the proxy support is within the clients used for various runtimes, so `reqwest`, `surf` and `attohttpc`, I might look into this, but it won't be a priority for sure

**Comment by durch** [comment]
[Added support for `reqwest::Proxy`, with `tokio` backend only](https://docs.rs/rust-s3/0.36.0-alpha.3/s3/bucket/struct.Bucket.html#method.set_proxy)
