### ISSUE TITLE
Stream uploads

### ISSUE THREAD

**Issue by dima74** [durch/rust-s3#40]
Similar to #10, but for uploads.

**Comment by durch** [comment]
@dima74 `put_object_stream` added in v0.19.0 -> https://github.com/durch/rust-s3/releases/tag/v0.19.0 and published to crates.io.

**Comment by meh** [comment]
Is there a reason `get_object_stream` takes an `io::Write` but `put_object_stream` doesn't take an `io::Read`?

I'd prefer to not have to save to a file before being able to upload it.

**Comment by durch** [comment]
@meh Probably, but can't think of it right now :), I'll revisit the implementation and get back to you, thanks for raising the inconsistency

**Comment by meh** [comment]
It might also be better for it to take AsyncRead and AsyncWrite in the async version, and Read and Write in the blocking one.

**Comment by durch** [comment]
@meh fixed in `0.22.0`, there are also new `tokio_put_stream_object` and `tokio_get_stream_object` `Bucket` methods that take `tokio::io::AsyncReadExt` and `tokio::io::AsyncWriteExt`. Their `futures` counter parts do not seem very practical to use yet...
