### ISSUE TITLE
Connection closed before message completed

### ISSUE THREAD

**Issue by r-ml** [durch/rust-s3#405]
**Describe the bug**
Getting a lot of `hyper: connection closed before message completed` errors which seem to be https://github.com/hyperium/hyper/issues/2136. \
`rust-s3` does not seem to configure any sort of `keepalive` value, I assume doing that fixes the issue. [AWS NodeJS SDK docs](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-reusing-connections.html) indicate a default value of 1000ms for `keepalive`. \
Another way would be to set `pool_idle_timeout` to match the S3 server value of 20s, according to comments in the hyper issue.

**To Reproduce**
Open a connection, sleep for more than 20s then try to use said connection.

**Expected behavior**
Connections remain open and usable.

**Environment**
 - Rust version: 1.80.1
 - lib version: 0.35.1

**Comment by r-ml** [comment]
Maybe something like https://github.com/r-ml/rust-s3/commit/f8d83103684a258be1129dfeaac35f527b5cb72e

**Comment by rml-showseeker** [comment]
> Another way would be to set pool_idle_timeout to match the S3 server value of 20s, according to comments in the hyper issue.
This does not seem to hold true. I've tried different pool_idle_timeout durations, as low as 5 seconds, but the error persists, although less frequent.

**Comment by r-ml** [comment]
> Another way would be to set pool_idle_timeout to match the S3 server value of 20s, according to comments in the hyper issue.

This does not seem to hold true. I've tried different pool_idle_timeout durations, as low as 5 seconds, but the error persists, although less frequent.
Even tcp_keepalive does not seem to help.

Oh well, retrying seems to be the solution for now. Seems wasteful though.
