### ISSUE TITLE
async call

### ISSUE THREAD

**Issue by Farkal** [durch/rust-s3#43]
I am trying to create a stream server with actix-web. 
So when an user is visiting a page i need to make a request to my s3 and send him the result. 
But i get an `S3Error(Reqwest(Error(BlockingClientInFutureContext, "http://localhost:9000/mybucket/")), State { next_error: None, backtrace: None })`.
I think it's because the lib doesn't use async reqwest client. Is there any plan to return future ?

**Comment by durch** [comment]
For sure, it been on a fuzzy roadmap, I'll try and back a beta version do for you to test

**Comment by durch** [comment]
@Farkal , made a quick and dirty implementation for getting objects, I'd appreciate if you'd let me know if it addresses the issues you've been having.`get_object_async` and `get_object_stream_async` are new methods on the `Bucket` struct. You can pull `v0.16.0-alpha` from crates.io and test it out.
