### ISSUE TITLE
Convert URL from "path-style" to "subdomain-style"

### ISSUE THREAD

**Issue by nastevens** [durch/rust-s3#45]
Amazon AWS is deprecating "path-style" access to S3 buckets, as detailed [in this blog post](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/). Prior to the sunset in September 2020, the rust-s3 URL handling logic will need to be updated to use "subdomain style".

**Comment by durch** [comment]
Should be fully done in v0.19.0, but I'll do an additional pass.
