### ISSUE TITLE
Fails with wasabi s3 storage

### ISSUE THREAD

**Issue by kpcyrd** [durch/rust-s3#51]
I'm trying to use rust-s3 to talk to the wasabi object storage, unfortunately I'm getting a http 400 reply with an empty response body. Also rust-s3 is having issues with the empty response and reacts like this:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: S3Error(SerdeXML(Error { pos: 1:1, kind: Syntax("Unexpected end of stream: no root element found") }), State { next_error: None, backtrace: None })', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

This is with 0.15.0, using this config (edited into src/bin/simple_crud.rs):
```rust
    const BUCKET: &str = "REDACTED";

    let region_name = "eu-central-1".to_string();
    let endpoint = "https://s3.wasabisys.com".to_string();
    let region = Region::Custom { region: region_name, endpoint };
    let credentials = Credentials::new(Some("REDACTED".into()), Some("REDACTED".into()), None, None);

    let bucket = Bucket::new(BUCKET, region, credentials)?;
```

I've tested both `list` and `put`, both of them fail in the same way.

**Comment by durch** [comment]
@kpcyrd thanks for raising this, I'll take a look and report back.

**Comment by durch** [comment]
Looking at their API docs, it seems they always use `us-east-1` as region, it would be great if you could test this snippet with `us-east-1` as the region_name. I'm playing this by ear for now, based on the API docs ->https://wasabi.com/wp-content/themes/wasabi/docs/API_Guide/index.html#t=topics%2FAuthenticating_Requests.htm%23XREF_37390_Authenticating

**Comment by kpcyrd** [comment]
It seems I've specified the endpoint incorrectly, it should've been `https://s3.eu-central-1.wasabisys.com`. It does work correctly now, sorry for the noise.

**Comment by durch** [comment]
No worries, super happy it works!
