### ISSUE TITLE
ec2 instance role support

### ISSUE THREAD

**Issue by slimm609** [durch/rust-s3#52]
I was trying to see if there was support for ec2 instance roles via the instance metadata?

**Comment by durch** [comment]
Hi @slimm609 not at the moment unfortunately, I'll see if I can squeeze it in in the next few days, not sure how complex reading the instance metadata is...

**Comment by durch** [comment]
@slimm609 started on implementing this, should be done fairly quickly

**Comment by durch** [comment]
@slimm609 version 0.18.1-beta pushed to crates.io, in case you'd like to test it
