### ISSUE TITLE
AWS Session Tokens not loaded from .credentials file

### ISSUE THREAD

**Issue by cutler-scott-newrelic** [durch/rust-s3#57]
When relying on loading a Credentials object from a specific profile, you should include the token as well if it is present within the .credentials file. For example, this is the format of my credentials file. aws_session_token and aws_security_token are both the same value. This format works with the current AWS S3 CLI, but I get an access denied when it's processed by this library.

```
[teamname/account_name]
aws_access_key_id=<redacted>
aws_secret_access_key=<redacted>
aws_session_token=<redacted>
aws_security_token=<redacted>

**Comment by durch** [comment]
@cutler-scott-newrelic  thank you for the report, I'll carve some time to implement over the weekend hopefully :)

**Comment by durch** [comment]
@cutler-scott-newrelic version `0.18.5` will be pushed to `crates.io` today, it should pull tokens from the file correctly

**Comment by cutler-scott-newrelic** [comment]
Awesome, thank you very much!
