### ISSUE TITLE
Plans for moving to std::future

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [durch/rust-s3#58]
Are there any current plans into moving to std::future or future 0.3? async/await has recently landed on stable build and both tokio and reqwest have alpha builds porting code to new futures model.

**Comment by durch** [comment]
@Jonathas-Conceicao yeah it's on a tentative roadmap for q1 or q2, I'm for the ecosystem to mature a bit. I'd be happy to take a PR and publish a beta version with async/await :)

**Comment by durch** [comment]
You can now track this progress over at #61 .

**Comment by durch** [comment]
@Jonathas-Conceicao, [v0.19.0](https://github.com/durch/rust-s3/releases/tag/v0.19.0) published to [crates.io](https://crates.io/crates/rust-s3)
