### ISSUE TITLE
Credentials::default() hangs forever when no credentials exist - 0.18.6

### ISSUE THREAD

**Issue by bn3t** [durch/rust-s3#62]
On a new computer where I have no credential setup for AWS when I call Credentials::default(), it hangs forever until a timeout. I've debugged the problem to the fact that it tries a request to http://169.254.169.254/latest/meta-data/iam/info. This service does not exist for us and it does not work.

**Comment by durch** [comment]
@bn3t thank you for the report, will look into failing more gracefully for that case. That timeout is caused by trying to get the credentials from the metadata service on an EC2 instance.

**Comment by durch** [comment]
@bn3t added a check for the ec2 uuid, this should fail instantly on a non ec2 machine when no credentials are available, version 0.18.7 published to `crates.io`

**Comment by bn3t** [comment]
Hi, now it panics. I find it not so ideal. Do you think you could make Credentials::new() return a S3Result? Wouldn't it be cleaner?
