### ISSUE TITLE
Async version of put_object

### ISSUE THREAD

**Issue by leocavalcante** [durch/rust-s3#72]
Can this be considered?

**Comment by durch** [comment]
Yes, should not be a big deal, will update the issue as it happens. Thanks for submitting

**Comment by leocavalcante** [comment]
Awesome, thank you!

For now, those who ended up here and are looking for a workaround, `tokio::task::spawn_blocking` should do the trick (trade-off, its a 500 threads pool, not suited for really large loads of `put_object`).
https://github.com/leocavalcante/list-load/blob/master/bin/upload.rs#L31

**Comment by durch** [comment]
@leocavalcante this has been added in v0.19.0, which, there are a bunch of breaking but ergonomic changes in there -> https://github.com/durch/rust-s3/releases/tag/v0.19.0

**Comment by leocavalcante** [comment]
Thank you so much, I'll be updating my list-load project.
