### ISSUE TITLE
Panic on client error

### ISSUE THREAD

**Issue by harasmussen** [durch/rust-s3#74]
If a client error occur (i.e trying to download an invalid bucket) while calling `get_object_stream()` it will save the xml formatted error message from S3 into the file. I would expect the function to return an Err() so my program can handle this case instead of continue as everything is okay.

It can be replicated by changing the bucket name to something bogus in the code snippet from the documentation: https://durch.github.io/rust-s3/s3/bucket/struct.Bucket.html#method.get_object_stream

Disclaimer: I'm new to Rust so I might miss something :)..

**Comment by harasmussen** [comment]
So I can use the 404 status code, but it still feels too late when file has been written to disk..

**Comment by durch** [comment]
Hi @harasmussen, unfortunately there is no validation on the lib side at the moment, I'll see if there is a nice way to add some sort of a callback based on the status codes that get returned. I agree that an `Err` would be a more ergonomic solution here.

 In the meantime I'd suggest checking the status code that gets returned by `get_object_stream`, I'm guessing anything greater that 204 should be treated as an error, not sure if they redirect tough...

**Comment by durch** [comment]
Circling back here, version `0.22.1` adds a `fail-on-err` feature that will surface an error on response codes >= 400.

**Comment by harasmussen** [comment]
@durch Thanks!
