### ISSUE TITLE
Broken build after updating from 0.19.3 --> 0.19.4

### ISSUE THREAD

**Issue by rabbitinspace** [durch/rust-s3#77]
Hi!

I've tried to update `rust-s3` from 0.19.3 to 0.19.4 and the new version changed return type of `Credentials::new` from `Credentials` to future (which is a breaking change). As I can see it was introduced here: 9c4ecf1e3fed7d6cfe19231880d1a812872ffd2a.

So, are you happy to revert it for 0.19.x? Or to have another non-async initializer?

**Comment by durch** [comment]
That’s an unfortunate regression, apologies for that, will have a revert for out tomorrow

**Comment by durch** [comment]
@rabbitinspace looking at the version code there are `new_blocking`, and `default_blocking` initializers for Credentials, would you be OK with using those, I'd like to avoid a `yank` and another new version.

I realize that we still broke the semver, and that its less then ideal, but another new `0.19.*` version might cause more confusion. If you can't use the sync initializers for whatever reason I'll be happy to  make the change, and publish `0.19.5`.

I'd actually encourage you to switch to 0.2.0, that blows this up into several crates, there will be a bit more controle over these types of changes

**Comment by rabbitinspace** [comment]
For now I’m happy to stay on 0.19.3 and will upgrade straight to 0.20.0 in the future.
(although I have a question about those blocking initializers, I can ask it in a separate issue)

I suppose I’m the only one who was affected by this breaking change given that 0.19.3 was yanked from crates.io and no one reported about it. So I’m going to close the issue. 

Thanks for looking into it!

**Comment by durch** [comment]
For sure, happy to help :)
