### ISSUE TITLE
rust-s3 should reexport aws-region and aws-creds

### ISSUE THREAD

**Issue by Ten0** [durch/rust-s3#80]
I get that somebody else may want to use aws-region/aws-creds without s3, hence the need for a separate crate.
However it's hard to use rust-s3 without these crates, and they have to be of the same version.
For this use, you usually want to re-export aws-region and aws-creds, making it easier on your users: they don't have to keep track of these dependencies, and the doc works better.

**Comment by durch** [comment]
@Ten0 thank you for the suggestion, v0.20.1 reexports` aws-region` as `region` and `aws-creds` as `creds`
