### ISSUE TITLE
AWS Session Tokens not loaded from .credentials file (partial)

### ISSUE THREAD

**Issue by browdus** [durch/rust-s3#81]
Basically the same as issue https://github.com/durch/rust-s3/issues/57. Pull request https://github.com/durch/rust-s3/pull/59 partially fixed the issue, but missed one of the fields, `aws_session_token`.

**Comment by durch** [comment]
published to crates.io with `0.21.0`

**Comment by browdus** [comment]
Perfect, thanks! It works like a charm.
