### ISSUE TITLE
Path style bucket access no longer possible after 0.20.1

### ISSUE THREAD

**Issue by Bobonium** [durch/rust-s3#88]
I just tried upgrading from 0.20.1 to the latest release, but had to realize that path style bucket access is no longer supported.
This is bad for minio compatibility. Minio does accept dns based bucket access, but it's simply never used by anyone in a kubernetes context as there's no easy way to properly generate these dns records there.

It'd be great if there was a way to configure the behavior here.

**Comment by durch** [comment]
@Bobonium thank you for raising the issue, I was unaware of the fact that minio does not support this, will provide a configuration flag

**Comment by durch** [comment]
@Bobonium pushed out a fix, you'll have to upgrade all the way `0.22.3` to get it tough :(, let me know if I can help with this. I've implemented it as a cargo feature for now:

```toml
rust-s3 = {version = "0.22.3", features = ["path-style"]}
```

**Comment by Bobonium** [comment]
@durch just tested it, and it works exactly as intended. Thanks a lot for the adjustment

**Comment by durch** [comment]
Happy to help :)
