### ISSUE TITLE
Path-style configuration in runtime 

### ISSUE THREAD

**Issue by iammichiel** [durch/rust-s3#96]
Hi there ! 

Thanks for your work on this bucket :) Really like the simplicity of it compared to other existing solutions in Rust ! 
Actually enjoyed integrating S3 into an app. Was definitely not the case using rusoto... 

Anyway, I would like to suggest making the `path-style` cargo feature a configuration flag. The problem with using it as a cargo feature flag is one cannot use multiple backends in the same app. Which is my case at the moment. Perhaps, it would be possible to add an optional boolean value to the `Region` to specify if it is path based or subdomain-based. 

Will try to make something work locally and try to send a PR in !

**Comment by durch** [comment]
@iammichiel I'm very happy to hear that. The feature implementation was always meant to be temporary, I'll be glad to have obsoleted :)
