### ISSUE TITLE
Add Support for rustls

### ISSUE THREAD

**Issue by arranf** [durch/rust-s3#98]
At the moment `rust-s3`'s backend uses reqwest and it's native-tls TLS/SSL feature. native-tls isn't as portable as rustls - it'd be a nice enhancement to support via feature flag compiling reqwest with different tls backends.

**Comment by durch** [comment]
@arranf published version `0.22.10` that adds `rustls-tls` feature flag to compile `reqwest` with its `rustls-tls` feature

**Comment by arranf** [comment]
@durch Can you make the same/similar changes with the aws creds repo?Thanks for making this change so quickly!

**Comment by durch** [comment]
@arranf `aws-creds` does not use any tls, `reqwest` is only used to get the metadata when running on an EC2 instance. So there is really nothing do to there :)
